### ISSUE TITLE
NotFoundError: Failed to create a directory: ./save/axial_fold0\tensorboard\train; No such file or directory

### ISSUE THREAD

**Issue by SaifurShatil** [MehrdadNoori/Attention-Guided-Version-of-2D-UNet-for-Automatic-Brain-Tumor-Segmentation#2]
NotFoundError: Failed to create a directory: ./save/axial_fold0\tensorboard\train; No such file or directory

**Comment by Mehrdad-Noori** [comment]
Can you please provide more details on the error? It would be nice if you share the piece of code that resulted in this error.
