### ISSUE TITLE
question in seg.nii

### ISSUE THREAD

**Issue by rezababaee759** [MehrdadNoori/Attention-Guided-Version-of-2D-UNet-for-Automatic-Brain-Tumor-Segmentation#4]
thanks for your job
i had requested for BraTS 2019 datset.when i tried to open seg.nii files and to convert them into png files, all of them were totally black. could you help?!

**Comment by Mehrdad-Noori** [comment]
I think it is because of the range of the pixel values in segmentation file (0,1,2,4 values).
You should try to re-scale it between 0,1 (or 0,255 based on the library) and then save it in PNG format.

**Comment by rezababaee759** [comment]
oh yes. thanks so much
