### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by JiexiPinkman** [MehrdadNoori/Attention-Guided-Version-of-2D-UNet-for-Automatic-Brain-Tumor-Segmentation#7]
When I run python train.py after one epoch ,I get this
![image](https://user-images.githubusercontent.com/35519251/85285424-7e5f0400-b4c3-11ea-9577-789bd1ef9ebc.png)

**Comment by Mehrdad-Noori** [comment]
It seems that there is a problem with validation data generator. 
Are you running the model on a cloud service?
Can you train the model without the validation generator for one epoch to see if the problem persists?

**Comment by JiexiPinkman** [comment]
Thank you for your help!  Yes ,lack of good gpu ,I run this on cloud gpu. I later fixed this bug by changing python 3.7 to 3.5 .The cloud supports changing the environment

**Comment by 675492062** [comment]
> Thank you for your help! Yes ,lack of good gpu ,I run this on cloud gpu. I later fixed this bug by changing python 3.7 to 3.5 .The cloud supports changing the environment

I fixed this bug by changing python 3.7 to 3.5 too, which is so Weird && Obscure
